### ISSUE TITLE
Broken with Django 1.9

### ISSUE THREAD

**Issue by bcoover** [krisfields/django-baker#10]
Just wanted to let you know that django-baker isn't working with Django 1.9. It appears that they changed how get_app works, so importing that now fails. Seems to be this change needed:

http://stackoverflow.com/questions/34069486/add-all-models-to-admin-site-django-1-9

**Comment by leonardoo** [comment]
Appconfigs changes everything in 1.7 and in 1.9 they drop the old api App/Models, this PR https://github.com/krisfields/django-baker/pull/13 fix it but broke all support to 1.7 and previous versions

**Comment by krisfields** [comment]
Sorry for the long delay.  I just updated everything to make it compatible with Django 1.10.  I imagine it should also work with 1.9 but I'm not sure.
