### ISSUE TITLE
ImproperlyConfigured at /create/

### ISSUE THREAD

**Issue by jonhairston** [krisfields/django-baker#11]
Specifying both 'fields' and 'form_class' is not permitted.

After running bake and going to the create view, I get the error mentioned in the title. This is a fresh bake with no modifications to the generated views.py.

However maybe it's left up to the user to decide which to use?

I'm using django 1.8.7

**Comment by krisfields** [comment]
Sorry for the really long delay.  I just fixed this now by commenting out one of them.
