### ISSUE TITLE
Not compatible with Py3k?

### ISSUE THREAD

**Issue by ghost** [krisfields/django-baker#12]
I've tried running this on a Python 3 project and I got the following error:

``` python
  File "-deleted-/lib/python3.4/site-packages/django_baker/management/commands/bake.py", line 54
    print app_label, model_names
                  ^
SyntaxError: Missing parentheses in call to 'print'

```

Seems like there is not reason to support Python 2 and Python 3, is this project still in active development? If so I can work on a pull request if desired.

**Comment by krisfields** [comment]
Fixed.
