### ISSUE TITLE
python 3 support?

### ISSUE THREAD

**Issue by nordbit** [krisfields/django-baker#2]
```
  File "/srv/bbb/lib/python3.4/site-packages/django_baker/management/commands/bake.py", line 54
    print app_label, model_names
                  ^
SyntaxError: Missing parentheses in call to 'print'
```

Python 2 only?

**Comment by marmalodak** [comment]
It's easy to make this work with Python 3.

diff --git a/django_baker/bakery.py b/django_baker/bakery.py
index ff04ef3..754e4f1 100644
--- a/django_baker/bakery.py
+++ b/django_baker/bakery.py
@@ -16,7 +16,7 @@ class Baker(object):
         """
             Iterates a dictionary of apps and models and creates all the necessary files to get up and running quickly.
         """
-        for app_label, models in apps_and_models.iteritems():
+        for app_label, models in apps_and_models.items():
             model_names = {model.__name__: self.get_field_names_for_model(model) for model in models}
             self.create_directories(app_label)
             self.create_init_files(app_label, model_names.keys(), models)
diff --git a/django_baker/management/commands/bake.py b/django_baker/management/commands/bake.py
index e602345..bd82cdc 100644
--- a/django_baker/management/commands/bake.py
+++ b/django_baker/management/commands/bake.py
@@ -51,7 +51,7 @@ class Command(BaseCommand):
         """
         if model_names:
             try:
-                print app_label, model_names
+                print(app_label, model_names)
                 return [get_model(app_label, model_name) for model_name in model_names]
             except:
                 raise CommandError("One or more of the models you entered for %s are incorrect." % app_label)

**Comment by timonweb** [comment]
Actually added pull request that adds Python 3 support: https://github.com/krisfields/django-baker/pull/3

**Comment by krisfields** [comment]
Thanks everyone!  I've merged in the PR.
