### ISSUE TITLE
Exception Value: 	  'EmailValidator' object has no attribute 'regex'

### ISSUE THREAD

**Issue by jlec** [krisfields/django-baker#8]
both with py2 and py3 I get this when accessing the baked admin view

Exception Type: 	AttributeError
Exception Value: 	

'EmailValidator' object has no attribute 'regex'

Exception Location: 	/usr/local/lib/python2.7/site-packages/django_baker/admin.py in is_urlfield, line 45

**Comment by krisfields** [comment]
Thanks!
